export default FakeData = [
    {id: 1, jobName: 'Job 1', address: '800 F St', employees: [
                                        {id: 1, firstName: 'Employee1', lastName: 'One', userType: 1},
                                        {id: 2, firstName: 'Employee1', lastName: 'Two', userType: 0},
                                        {id: 3, firstName: 'Employee1', lastName: 'Three', userType: 1},
                                        {id: 4, firstName: 'Employee1', lastName: 'Four', userType: 0},
                                        {id: 5, firstName: 'Employee1', lastName: 'Five', userType: 0},
                                        {id: 6, firstName: 'Employee1', lastName: 'Six', userType: 1},
                                        {id: 7, firstName: 'Employee1', lastName: 'Seven', userType: 0},
                                        {id: 8, firstName: 'Employee1', lastName: 'Eight', userType: 1},
                                        {id: 9, firstName: 'Employee1', lastName: 'Nine', userType: 0},
                                        {id: 10, firstName: 'Employee1', lastName: 'Ten', userType: 0},
                                        {id: 11, firstName: 'Employee1', lastName: 'Eleven', userType: 0},
        ]},
    {id: 2, jobName: 'Job 2', address: '900 A St', employees: [
                                        {id: 1, firstName: 'Employee2', lastName: 'One', userType: 1},
                                        {id: 2, firstName: 'Employee2', lastName: 'Two', userType: 0},
                                        {id: 3, firstName: 'Employee2', lastName: 'Three', userType: 1},
                                        {id: 4, firstName: 'Employee2', lastName: 'Four', userType: 0},
                                        {id: 5, firstName: 'Employee2', lastName: 'Five', userType: 0},
                                        {id: 6, firstName: 'Employee2', lastName: 'Six', userType: 1},
                                        {id: 7, firstName: 'Employee2', lastName: 'Seven', userType: 0},
                                        {id: 8, firstName: 'Employee2', lastName: 'Eight', userType: 1},
                                        {id: 9, firstName: 'Employee2', lastName: 'Nine', userType: 0},
                                        {id: 10, firstName: 'Employee2', lastName: 'Ten', userType: 0},
                                        {id: 11, firstName: 'Employee2', lastName: 'Eleven', userType: 0},
        ]},
    {id: 3, jobName: 'Job 3', address: '300 B St', employees: [
                                        {id: 1, firstName: 'Employee3', lastName: 'One', userType: 1},
                                        {id: 2, firstName: 'Employee3', lastName: 'Two', userType: 0},
                                        {id: 3, firstName: 'Employee3', lastName: 'Three', userType: 1},
                                        {id: 4, firstName: 'Employee3', lastName: 'Four', userType: 0},
                                        {id: 5, firstName: 'Employee3', lastName: 'Five', userType: 0},
                                        {id: 6, firstName: 'Employee3', lastName: 'Six', userType: 1},
                                        {id: 7, firstName: 'Employee3', lastName: 'Seven', userType: 0},
                                        {id: 8, firstName: 'Employee3', lastName: 'Eight', userType: 1},
                                        {id: 9, firstName: 'Employee3', lastName: 'Nine', userType: 0},
                                        {id: 10, firstName: 'Employee3', lastName: 'Ten', userType: 0},
                                        {id: 11, firstName: 'Employee3', lastName: 'Eleven', userType: 0},
        ]},
    {id: 4, jobName: 'Job 4', address: '400 C St', employees: [
                                        {id: 1, firstName: 'Employee4', lastName: 'One', userType: 1},
                                        {id: 2, firstName: 'Employee4', lastName: 'Two', userType: 0},
                                        {id: 3, firstName: 'Employee4', lastName: 'Three', userType: 1},
                                        {id: 4, firstName: 'Employee4', lastName: 'Four', userType: 0},
                                        {id: 5, firstName: 'Employee4', lastName: 'Five', userType: 0},
                                        {id: 6, firstName: 'Employee4', lastName: 'Six', userType: 1},
                                        {id: 7, firstName: 'Employee4', lastName: 'Seven', userType: 0},
                                        {id: 8, firstName: 'Employee4', lastName: 'Eight', userType: 1},
                                        {id: 9, firstName: 'Employee4', lastName: 'Nine', userType: 0},
                                        {id: 10, firstName: 'Employee4', lastName: 'Ten', userType: 0},
                                        {id: 11, firstName: 'Employee4', lastName: 'Eleven', userType: 0},
        ]},   
    {id: 5, jobName: 'Job 5', address: '500 D St', employees: [
                                        {id: 1, firstName: 'Employee5', lastName: 'One', userType: 1},
                                        {id: 2, firstName: 'Employee5', lastName: 'Two', userType: 0},
                                        {id: 3, firstName: 'Employee5', lastName: 'Three', userType: 1},
                                        {id: 4, firstName: 'Employee5', lastName: 'Four', userType: 0},
                                        {id: 5, firstName: 'Employee5', lastName: 'Five', userType: 0},
                                        {id: 6, firstName: 'Employee5', lastName: 'Six', userType: 1},
                                        {id: 7, firstName: 'Employee5', lastName: 'Seven', userType: 0},
                                        {id: 8, firstName: 'Employee5', lastName: 'Eight', userType: 1},
                                        {id: 9, firstName: 'Employee5', lastName: 'Nine', userType: 0},
                                        {id: 10, firstName: 'Employee5', lastName: 'Ten', userType: 0},
                                        {id: 11, firstName: 'Employee5', lastName: 'Eleven', userType: 0},
    ]},                              
]