name: Automated Testing


on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:  
    name: Running Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [15.x]
  
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ./time
        run: npm install
      - name: Run Tests
        working-directory: ./time
        run: npm test
